export type { allProductInterface } from './all.interface'
export type { oneProductInterface } from './one.interface'
export type { createdProductInterface } from './created-product.interface'
export type { updateProductInterface } from './update.interface'
export type { daletedProductInterface } from './daleted.interface'